name: frontend docker image publish flow

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - name: Frontend Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ secrets.DOCKER_USER }}/s7frontend
        tags: latest
        registry: docker.io
        dockerfile: ./Frontend/angularclient/Dockerfile
        directory: ./Frontend/angularclient
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
